export const QUERY = `
    query{
        findPaginaSobreSingleton{
        data{
        banners{
            iv{
            banner{
                titulo
                subTitulo
                cartao
                imagem{
                url
                }
            }
            }
        }
        titulo{
            iv
        }
        conteudoSuperior{
            iv{
            subTitulo
            alinhamento
            conteudo
            imagem{
                url
            }
            }
        }
        conteudoInferior{
            iv{
            subTitulo
            alinhamento
            conteudo
            imagem{
                url
            }
            }
        }
        imagens{
            iv{
            url
            }
        }
        }
    }
    }
`