export const QUERY = `
query{
    findConfiguracaoSingleton{
      data{
        carrossel{
          iv{
            preTitulo
            titulo
            limite
            itens{
              titulo
              imagem{
                url
              }
              navegacao
              conteudo
            }
          }
        }
        tema{
          iv{
            primaria
            secundaria
            terciario
            quaternaria
            branco
            bordaTituloInferior
          }
        }
      }
    }
  }

`