import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import './globals.css'
import Menu from '@/components/menu/layout'
import Footer from '@/components/Footer/layout'

const inter = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Secretaria de turismo São Joaquim',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="pt-BR">
      <body className={`${inter.className}`}>
        <Menu />
        <div className='layout_main'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
