export const QUERY = `
  query{
    findPaginaInicioSingleton{
        data{
          banners{
              iv{
                  banner{
                    preTitulo
                    titulo
                    subTitulo
                    cartao
                    imagem{
                      url
                    }
                  }
              }
            }
            tituloConteudoApresentacao{
                iv
            }
            imagemConteudoApresentacao{
              iv{
                url
              }
            }
            conteudo{
                iv
            }
            secoes{
                iv{
                  pergunta
                  resposta
                }
            }
            titulo{
                iv
            }
            subTitulo{
                iv
            }
            preTituloInferior{
                iv
            }
              tituloInferior{
                iv
            }
            imagemInferior{
                iv{
                  url
                }
              }
        }
    }
  }
`