export const QUERY = 
    `
        query{
            findPaginaEventosSingleton{
                data{
                    banners{
                        iv{
                            banner{
                                cartao
                                imagem{
                                    url
                                }
                                subTitulo
                                titulo
                            }
                        }
                    }
                    conteudo{
                        iv
                    }
                    subTitulo{
                        iv
                    }
                    titulo{
                        iv
                    }
                }
            }
        }
    `