export const QUERY =
  `
    query{
      findPaginaEventosSingleton{
          data{
             banners{
              iv{
                banner{
                  preTitulo
                  titulo
                  subTitulo
                  cartao
                  imagem{
                    url
                  }
                  
                }
              }
            }
              titulo{
                iv
              }
            subTitulo{
              iv
            }
            conteudo{
              iv
            }
            
          }
      }
    }
    `

export const QUERY_LIST_EVENTS = `
  query{
    queryMesesContents{
      data{
        nome{
          iv
        }
        mes{
          iv
        }
        eventosPorMes{
          iv{
            data{
              nome{
                iv
              }
              categoria{
                iv
              }
              publico{
                iv
              }
              duracao{
                iv
              }
              local{
                iv
              }
              dataDe{
                iv
              }
              dataFim{
                iv
              }
              resumo{
                iv
              }
              resumoImagem{
                iv{
                  url
                }
              }
              descritivo{
                iv
              }
              detalheConteudo{
                iv
              }
              imagens{
                iv{
                  url
                }
              }
              secoes{
                iv{
                  titulo
                  conteudo
                  galeria{
                    url
                  }
                }
              }
              slug{
                iv
              }
              banners{
                iv{
                  banner{
                    preTitulo
                    titulo
                    subTitulo
                    cartao
                    imagem{
                      url
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
`

export const QUERY_EVENTO = (option: any, params: any) => {

  return `
  query{
    queryEventoContents(filter:"data/${option}/iv eq '${params}'"){
    data{
      
        nome{
        iv
        }
        categoria{
        iv
        }
        publico{
        iv
        }
        duracao{
        iv
        }
        resumo{
        iv
        }
        resumoImagem{
        iv{
            url
        }
        }
        descritivo{
        iv
        }
        detalheConteudo{
        iv
        }
        imagens{
        iv{
            url
        }
        }
        secoes{
        iv{
            titulo
            conteudo
            galeria{
            url
            }
        }
        }  
        slug{
        iv
        }
    }
    }
}
  `
}